services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${db_owner}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
